<a href="https://colab.research.google.com/github/tanvihole25-creator/Data-Science_lab_78/blob/main/p3_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[2,4,5,6], [12,13,14,15], [9, 10, 11, 18]])
a

array([[ 2,  4,  5,  6],
       [12, 13, 14, 15],
       [ 9, 10, 11, 18]])

In [ ]:
a[0]

np.int64(1)

In [ ]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [ ]:
a[:3]

array([10,  2,  3])

In [ ]:
b = a[4:]
b
b[0] = 10
a

array([10,  2,  3,  4, 10,  6])

In [ ]:
a = np.array([[2,4,5,6], [12,13,14,15], [9, 10, 11, 18]])
a

array([[ 2,  4,  5,  6],
       [12, 13, 14, 15],
       [ 9, 10, 11, 18]])

In [ ]:
a[1, 3]

np.int64(15)

In [ ]:
a.ndim

2

In [ ]:
a.shape
len(a.shape) == a.ndim

True

In [ ]:
a.size
import math
a.size == math.prod(a.shape)

True

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
# Create an empty array with 2 elements
np.empty(2)

array([4.94065646e-324, 6.55116354e-310])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.reshape(a, shape=(1, 6), order='C')

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])