<a href="https://colab.research.google.com/github/tanvihole25-creator/Data-Science_lab_78/blob/main/p3_78.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

# Create a 3x3 square matrix from user input
print("Enter the elements of the 3x3 matrix row by row.")
print("Please enter 3 space-separated numbers for each row and press Enter.")

matrix_elements = []
for i in range(3):
    while True:
        try:
            row_str = input(f"Enter row {i+1} (e.g., '1 2 3'): ")
            row = list(map(float, row_str.split()))
            if len(row) == 3:
                matrix_elements.append(row)
                break
            else:
                print("Please enter exactly 3 numbers for the row.")
        except ValueError:
            print("Invalid input. Please enter numbers separated by spaces.")

matrix = np.array(matrix_elements)

print("\nOriginal 3x3 matrix (from your input):")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("\nDeterminant of the matrix:")
print(determinant)

Enter the elements of the 3x3 matrix row by row.
Please enter 3 space-separated numbers for each row and press Enter.
Enter row 1 (e.g., '1 2 3'): 1 2 3 
Enter row 2 (e.g., '1 2 3'): 1 5 1
Enter row 3 (e.g., '1 2 3'): 6 1 8

Original 3x3 matrix (from your input):
[[1. 2. 3.]
 [1. 5. 1.]
 [6. 1. 8.]]

Determinant of the matrix:
-51.999999999999986


In [10]:
import numpy as np

# Check if the matrix is invertible (determinant is not zero)
if np.linalg.det(matrix) != 0:
    # Compute the inverse of the matrix
    inverse_matrix = np.linalg.inv(matrix)

    print("Original matrix:")
    print(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("The matrix is singular and does not have an inverse.")

Original matrix:
[[ 7.  5.  3.]
 [ 1.  5.  9.]
 [ 4.  6. 10.]]

Inverse of the matrix:
[[-0.06666667 -0.53333333  0.5       ]
 [ 0.43333333  0.96666667 -1.        ]
 [-0.23333333 -0.36666667  0.5       ]]


In [11]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([10, 20])

print("Coefficient matrix A:")
print(A)
print("\nConstant vector B:")
print(B)

# Solve the system of linear equations Ax = B
solution = np.linalg.solve(A, B)

print("\nSolution (x, y):")
print(solution)

# Verify the solution
x, y = solution
print(f"\nVerification:")
print(f"2*{x} + 3*{y} = {2*x + 3*y} (expected 10)")
print(f"4*{x} + 5*{y} = {4*x + 5*y} (expected 20)")

Coefficient matrix A:
[[2 3]
 [4 5]]

Constant vector B:
[10 20]

Solution (x, y):
[5. 0.]

Verification:
2*5.0 + 3*0.0 = 10.0 (expected 10)
4*5.0 + 5*0.0 = 20.0 (expected 20)
